apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: registry
- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    name: registry-registry-role
  roleRef:
    kind: ClusterRole
    name: system:registry
  subjects:
  - kind: ServiceAccount
    name: registry
    namespace: hipchat-kudos
  userNames:
  - system:serviceaccount:hipchat-kudos:registry
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      docker-registry: default
    name: docker-registry
  spec:
    replicas: 1
    selector:
      docker-registry: default
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          docker-registry: default
      spec:
        containers:
        - env:
          - name: REGISTRY_HTTP_ADDR
            value: :5000
          - name: REGISTRY_HTTP_NET
            value: tcp
          - name: REGISTRY_HTTP_SECRET
            value: 9DotQgBwzkqJS0dC8UQVEqracVUVhgC/SsNLfLe196U=
          - name: REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ENFORCEQUOTA
            value: "false"
          image: openshift/origin-docker-registry:v3.7.1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          name: registry
          ports:
          - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /registry
            name: registry-storage
        securityContext: {}
        serviceAccount: registry
        serviceAccountName: registry
        volumes:
        - emptyDir: {}
          name: registry-storage
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      docker-registry: default
    name: docker-registry
  spec:
    clusterIP: 172.30.254.23
    ports:
    - name: 5000-tcp
      port: 5000
      targetPort: 5000
    selector:
      docker-registry: default
    sessionAffinity: ClientIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
